# Generated by Django 6.0.3 on 2026-03-29 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Horario disponible',
                'verbose_name_plural': 'Horarios disponibles',
                'ordering': ['fecha', 'hora_inicio'],
                'unique_together': {('fecha', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atencion', models.CharField(choices=[('presencial', 'Presencial'), ('telefonica', 'Telefónica'), ('virtual', 'Virtual')], max_length=15, verbose_name='Tipo de atención')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('confirmada', 'Confirmada'), ('cumplida', 'Cumplida'), ('no_asistio', 'No asistió'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de la consulta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL, verbose_name='Beneficiario')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.horariodisponible', verbose_name='Horario')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(verbose_name='¿Asistió?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='citas.cita', verbose_name='Cita')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
