# Generated by Django 6.0.3 on 2026-03-31 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del caso')),
                ('sala_juridica', models.CharField(choices=[('civil', 'Civil'), ('laboral', 'Laboral'), ('penal', 'Penal'), ('publico', 'Público'), ('familia', 'Familia')], max_length=20, verbose_name='Sala jurídica')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('en_estudio', 'En estudio'), ('asignado', 'Asignado'), ('cerrado', 'Cerrado'), ('rechazado', 'Rechazado')], default='en_estudio', max_length=20, verbose_name='Estado del caso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to=settings.AUTH_USER_MODEL, verbose_name='Beneficiario')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.caso', verbose_name='Caso'),
        ),
    ]
