# Generated by Django 6.0.3 on 2026-04-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_caso_cita_caso'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='estudiante_asignado',
            field=models.CharField(blank=True, default='No registra', max_length=200, verbose_name='Estudiante asignado'),
        ),
    ]
