# Generated by Django 5.2.8 on 2026-04-07 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clean_estudiante_asignado(apps, schema_editor):
    Caso = apps.get_model('citas', 'Caso')
    Usuario = apps.get_model('usuarios', 'Usuario')
    valid_ids = {str(user.pk) for user in Usuario.objects.all()}
    for caso in Caso.objects.all():
        value = caso.estudiante_asignado
        if not value:
            continue
        if str(value) not in valid_ids:
            caso.estudiante_asignado = None
            caso.save()


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_caso_estudiante_asignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='estudiante_asignado',
            field=models.CharField(blank=True, default='No registra', max_length=200, null=True, verbose_name='Estudiante asignado'),
        ),
        migrations.RunPython(clean_estudiante_asignado, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='caso',
            name='estudiante_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'estudiante'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante asignado'),
        ),
    ]
