# Generated by Django 6.0.3 on 2026-04-17 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_caso_estudiante_asignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada por'),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, default='', verbose_name='Motivo de cancelación'),
        ),
    ]
