# Generated by Django 6.0.3 on 2026-04-23 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_cita_cancelada_por_cita_motivo_cancelacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_reagendamiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reagendamiento'),
        ),
        migrations.AddField(
            model_name='cita',
            name='horario_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_reagendadas_desde', to='citas.horariodisponible', verbose_name='Horario anterior'),
        ),
        migrations.AddField(
            model_name='cita',
            name='reagendada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_reagendadas', to=settings.AUTH_USER_MODEL, verbose_name='Reagendada por'),
        ),
    ]
