# Generated by Django 5.2.8 on 2026-04-07 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acepta_tratamiento', models.BooleanField(default=False, verbose_name='Acepta tratamiento de datos')),
                ('fecha_autorizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de autorización')),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de registro')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacion', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Autorización',
                'verbose_name_plural': 'Autorizaciones',
            },
        ),
    ]
