# Generated by Django 6.0.3 on 2026-04-17 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0004_alter_caso_estudiante_asignado'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10, verbose_name='Canal de envío')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=10, verbose_name='Estado del envío')),
                ('fecha_intento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del intento')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('mensaje_error', models.TextField(blank=True, default='', verbose_name='Mensaje de error')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='citas.cita', verbose_name='Cita')),
            ],
            options={
                'verbose_name': 'Log de Recordatorio',
                'verbose_name_plural': 'Logs de Recordatorios',
                'ordering': ['-fecha_intento'],
            },
        ),
    ]
