# Generated by Django 6.0.3 on 2026-04-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrecordatorio',
            name='intentos',
            field=models.IntegerField(default=1, verbose_name='Número de intentos'),
        ),
    ]
