# Generated by Django 6.0.3 on 2026-05-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricasAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('total_citas', models.IntegerField(default=0, verbose_name='Total de citas')),
                ('asistidas_count', models.IntegerField(default=0, verbose_name='Citas asistidas')),
                ('no_asistio_count', models.IntegerField(default=0, verbose_name='Citas no asistidas')),
                ('porcentaje_asistencia', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje asistencia')),
                ('porcentaje_inasistencia', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje inasistencia')),
            ],
            options={
                'verbose_name': 'Métricas de asistencia',
                'verbose_name_plural': 'Métricas de asistencia',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
